### ISSUE TITLE
Allow specifying a browser other than the default

### ISSUE THREAD

**Issue by thtliife** [servian/awskeyring#71]
**Is your feature request related to a problem? Please describe.**
I am unable to use the console command to open a specific browser. This is useful to me when working with multiple accounts, or for some services where my default browser (safari 14) is not well supported.

**Describe the solution you'd like**
Implement a --browser, -b option to the console method allowing to specify a browser

**Comment by tristanmorgan** [comment]
Hi @thtliife ,

That sounds like a good suggestion. I'll have a go at implementing it in the next few days. 

Until then the --no-open flag will print out the signin url so you can paste it into your other browser.

T.

**Comment by thtliife** [comment]
Got a pr incoming 
Just making sure tests and such pass

**Comment by tristanmorgan** [comment]
I've got a branch and some sketchy code. I will turn it into a PR in a few days.

**Comment by tristanmorgan** [comment]
updated Wiki with details about customising your [list of browsers](https://github.com/servian/awskeyring/wiki/Awskeyring-Config-file).
